apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stage-test
  namespace: gitops
spec:
  destination:
    namespace: stage-test
    server: https://kubernetes.default.svc
  project: default
  source:
    path: overlays/test
    repoURL: https://github.com/dstraub/do288-sample.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true


