apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stage-prod
  namespace: openshift-gitops
spec:
  destination:
    namespace: stage-prod
    server: https://kubernetes.default.svc
  project: default
  source:
    path: overlays/prod
    repoURL: https://github.com/dstraub/do288-sample.git
    targetRevision: HEAD

